# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('upload_file', models.FileField(upload_to='')),
                ('add_count', models.IntegerField(default='0')),
                ('usid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
    ]
