# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-16 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_uploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
