# Generated by Django 3.2.25 on 2026-03-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_uploadmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='original_filename',
            field=models.CharField(default='', max_length=300),
        ),
    ]
