# Generated by Django 3.2.25 on 2026-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_uploadmodel_original_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Unknown', max_length=200)),
                ('filename', models.CharField(default='', max_length=300)),
                ('cnn_score', models.FloatField(default=0)),
                ('lstm_score', models.FloatField(default=0)),
                ('mrn_score', models.FloatField(default=0)),
                ('ensemble_score', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
