# Generated by Django 3.2.25 on 2026-04-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_registermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='userid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
